actions/urls.py
from django.conf.urls.static import static
from src import settings
from django.urls import path, include
from .views import actions, actions_history

urlpatterns = [
    path('', actions, name='action_main'),
    path('history/', actions_history, name='actions_history'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she/urls.py
from django.urls import path
from she.views import she_main


urlpatterns = [
    path('', she_main, name='she_main'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new



from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
    path('actions/', include(('actions.urls', 'actions'), namespace='actions')),
    path('attendance/', include(('attendance.urls', 'recognition_page'), namespace='attendance')),
    path('improvements/', include(('improvements.urls', 'improvements'), namespace='improvements')),
    path('notice-board/', include(('notice_board.urls', 'notice_board'), namespace='notice-board')),
    path('recognitions/', include(('recognitions.urls', 'recognition_page'), namespace='recognitions')),
    path('she/', include(('she.urls', 'she_page'), namespace='she')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actions/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Group
from authapp.models import UserModel

# Create your models here.

class ActionTaskManagerModel(models.Model):
    STATUS_CHOICES = (
        ('draft', 'DRAFT'),
        ('canceled', 'CANCELED'),
        ('completed', 'COMPLETED'),
    )
    objects = models.Manager()
    creation_date = models.DateField(auto_now_add=True, verbose_name="Creation date")
    issue_name = models.CharField(max_length=255, blank=False, verbose_name="Issue title")
    action_text = models.TextField(blank=True, verbose_name="Issue description")
    solution_text = models.TextField(blank=True, verbose_name="Issue action")
    assigned_user = models.ManyToManyField(
        UserModel,
        through='AssignedToAction',
        verbose_name="Assigned"
    )
    deadline_date = models.DateField(verbose_name="Deadline date")
    action_status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='draft')
    action_group = models.ForeignKey(Group, blank=False, default="1", on_delete=models.CASCADE, verbose_name="Action groups")

    def __str__(self):
        return self.issue_name

    def get_assigned_user(self):
        return ",".join([str(p.pk) for p in self.assigned_user.all()])
    class Meta:
        verbose_name = 'Action'
        verbose_name_plural = 'Actions'
        ordering = ['-action_status', '-id']

#model that used for action assignment
class AssignedToAction(models.Model):
    person = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    action = models.ForeignKey(ActionTaskManagerModel, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.action

    class Meta:
        ordering = ('action',)

actions/forms.py
from django import forms
from .models import *

from django.contrib.admin import widgets
class DateInput(forms.DateInput):
    input_type = 'date'
class ActionCreateForm(forms.ModelForm):
    class Meta:
        model = ActionTaskManagerModel
        fields = [
            'issue_name',
            'action_text',
            'solution_text',
            'assigned_user',
            'deadline_date',
            'action_status'
        ]
        widgets = {
            'deadline_date': DateInput(),
        }

actions/views.py
import time
import json
from tokenize import group 
from django.shortcuts import render, redirect
from .models import ActionTaskManagerModel
from authapp.models import UserModel
from django.http import JsonResponse
from django.http import HttpResponseRedirect
# Create your views here.


from django.contrib.auth.decorators import login_required
@login_required(login_url='/login/')
def actions(request):
    user_group = UserModel.objects.get(id=request.user.id).groups.first()

    unactive_action_list = ActionTaskManagerModel.objects.filter(action_group=user_group).exclude(action_status='draft').order_by('-id')[:5]
    active_actions_list = ActionTaskManagerModel.objects.filter(action_group=user_group, action_status='draft')
    user_profile_list = UserModel.objects.filter(groups=user_group)

    response_data = {}
    group_members_count = user_profile_list.count()
    
    if request.method == "GET" and request.GET.get('action') == 'get_data':
        action_pk = request.GET.get("action_pk", 1)
        selected_action = ActionTaskManagerModel.objects.get(id = action_pk)
        
        response_data['action_pk'] = action_pk
        response_data['issue_name'] = selected_action.issue_name
        response_data['action_text'] = selected_action.action_text
        response_data['solution_text'] = selected_action.solution_text
        response_data['action_status'] = selected_action.action_status
        response_data['assigned_users'] = selected_action.get_assigned_user()
        response_data['deadline_date'] = selected_action.deadline_date

        return JsonResponse(response_data)

    if request.POST.get('action') == 'add':
        render_response = add_action(request, user_group)
        return render_response
    if request.POST.get('action') == 'edit':
        render_response = update_action(request, user_group)
        return render_response 
    return render(request, 'actions_main.html', {
        'unactive_actions': unactive_action_list, 
        'active_actions':  active_actions_list,
        'user_profile_list': user_profile_list , 
        'group_members': group_members_count,
        })

def add_action(request, user_group):
    selected_status= request.POST.get('selected_status')
    deadline_date = request.POST.get('deadline_date')
    issue_name = request.POST.get('issue_name')
    action_text = request.POST.get('action_text')
    solution_text = request.POST.get('solution_text')
    assigned_user_list = request.POST.get('assigned_user')
    assigned_user = assigned_user_list.split(',')
    
    new_action = ActionTaskManagerModel.objects.create(
            issue_name = issue_name,
            action_text = action_text,
            solution_text = solution_text,            
            deadline_date = deadline_date,
            action_status = selected_status,
            action_group =  user_group
        )
    for user in assigned_user:
        new_action.assigned_user.add(user)
    new_action.save()
    time.sleep(2)
    unactive_action_list = ActionTaskManagerModel.objects.filter(action_group=user_group).exclude(action_status='draft').order_by('-id')[:5]
    active_actions_list = ActionTaskManagerModel.objects.filter(action_group=user_group, action_status='draft')
    user_profile_list =  UserModel.objects.filter(groups =  user_group)
    group_members_count =  UserModel.objects.filter(groups =  user_group).count()

    return render(request, 'action_listing.html', {
        'unactive_actions': unactive_action_list, 
        'active_actions':  active_actions_list,
        'user_profile_list': user_profile_list , 
        'group_members': group_members_count,
    })
def update_action(request, user_group):
    instance = ActionTaskManagerModel.objects.get(id=request.POST.get('action_pk'))
    selected_status = request.POST.get('selected_status')
    deadline_date = request.POST.get('deadline_date')
    issue_name = request.POST.get('issue_name')
    action_text = request.POST.get('action_text')
    solution_text = request.POST.get('solution_text')

    instance.issue_name=issue_name
    instance.action_text=action_text
    instance.solution_text=solution_text
    instance.action_status=selected_status
    instance.deadline_date=deadline_date
    
    #Connecting user with action
    assigned_user_list = request.POST.get('assigned_user')
    assigned_user = assigned_user_list.split(',')
    try:
        for user in assigned_user:
            instance.assigned_user.add(user)
    except:
        changed = False
    #Removing user from action connections
    unassigned_user_list = request.POST.get('unassigned_user')
    if unassigned_user_list != "":
        unassigned_user = unassigned_user_list.split(',')
        try:
            for user in unassigned_user:
                instance.assigned_user.remove(user)
        except:
            changed = False
    instance.save()

    unactive_action_list = ActionTaskManagerModel.objects.filter(action_group=user_group).exclude(action_status='draft').order_by('-id')[:5]
    active_actions_list = ActionTaskManagerModel.objects.filter(action_group=user_group, action_status='draft')
    user_profile_list =  UserModel.objects.filter(groups =  user_group)
    group_members_count =  UserModel.objects.filter(groups =  user_group).count()

    return render(request, 'action_listing.html', {
        'unactive_actions': unactive_action_list, 
        'active_actions':  active_actions_list,
        'user_profile_list': user_profile_list , 
        'group_members': group_members_count,
        })
@login_required(login_url='/login/')
def actions_history(request):
    user_group = UserModel.objects.get(id=request.user.id).groups.first()
    action_list = ActionTaskManagerModel.objects.filter(action_group=user_group)
    user_profile_list = UserModel.objects.filter(groups=user_group)
    group_members_count = user_profile_list.count()
    if request.POST.get('action') == 'edit':
        instance = ActionTaskManagerModel.objects.get(id=request.POST.get('action_pk'))
        selected_status = request.POST.get('selected_status')
        deadline_date = request.POST.get('deadline_date')
        issue_name = request.POST.get('issue_name')
        action_text = request.POST.get('action_text')
        solution_text = request.POST.get('solution_text')

        instance.issue_name=issue_name
        instance.action_text=action_text
        instance.solution_text=solution_text
        instance.action_status=selected_status
        instance.deadline_date=deadline_date
        
        #Connecting user with action
        assigned_user_list = request.POST.get('assigned_user')
        assigned_user = assigned_user_list.split(',')
        try:
            for user in assigned_user:
                instance.assigned_user.add(user)
        except:
            changed = False
        #Removing user from action connections
        unassigned_user_list = request.POST.get('unassigned_user')
        if unassigned_user_list != "":
            unassigned_user = unassigned_user_list.split(',')
            try:
                for user in unassigned_user:
                    instance.assigned_user.remove(user)
            except:
                changed = False
        instance.save()

        user_group = UserModel.objects.get(id=request.user.id).groups.first()
        action_list = ActionTaskManagerModel.objects.filter(action_group=user_group).exclude(action_status='draft')
        user_profile_list = UserModel.objects.filter(groups=user_group)
        group_members_count = user_profile_list.count()

        return render(request, 'all_actions.html', {
            'all_actions': action_list, 
            'user_profile_list': user_profile_list , 
            'group_members': group_members_count,
            })
    return render(request, 'actions_history.html', {
    'all_actions': action_list, 
    'user_profile_list': user_profile_list , 
    'group_members': group_members_count,
    })

actions/templates/actions_history.html
{% extends "base.html" %}
{% load static %}

{% block page-title %} | Actions{% endblock page-title %}
{% block styles %}
    <link rel="stylesheet" href="">
    <link rel="stylesheet" type="text/css" href="{% static '/css/action.css' %}">
{% endblock styles %}
{% block content %}
    <div>
        <div class="btns">
            <a href="{% url 'actions:action_main' %}" onclick="openForm()">
                <img src="{% static '/img/back.png' %}" alt="update page"> 
                <span class="add">Back to Active Actions</span>
            </a>
        </div>
        <h2 class="page-title">Actions History</h2>
    </div>
    <table class="actions_table" style="width: 100%;">
        {% include 'all_actions.html' %}
    </table>
    <div class="form_container" id="edit-popup">
        <div class="action_form_editing">
            <h3 class="form-title" style="text-align: center;">Editing action <span name="result"></span></h3>
            <form id="action_editing_form" method="POST" value="">
                {% csrf_token %}
                <fieldset class="checkboxes">
                    <span class="label">Status</span>
                    <div class="chebox_item in_progress draft">
                        <input type="radio" id="in_progress_edit" name="status" value="draft"
                           {% if action.action_status == "draft" %}
                            checked
                           {% endif%}
                        >
                        <label for="in_progress_edit"><img src="{% static '/img/in_progress.svg' %}" alt="Cancel"></label>
                    </div>

                    <div class="chebox_item done completed">
                        <input type="radio" id="done_edit" name="status" value="completed"
                           {% if action.action_status == "completed" %}
                              checked
                           {% endif%}
                        >
                        <label for="done_edit"><img src="{% static '/img/done.svg' %}" alt="Cancel"></label>
                    </div>

                    <div class="chebox_item cancel canceled">
                        <input type="radio" id="cancel_edit" name="status" value="canceled"
                           {% if action.action_status == "canceled" %}
                              checked
                           {% endif%}
                        >
                        <label for="cancel_edit"><img src="{% static '/img/cancel.svg' %}" alt="Cancel"></label>
                    </div>

                </fieldset>
                <div class="form_fields">
                    <div class="deadline">
                        <span class="label">Deadline date</span>
                        <input type="date" id="deadline_date" value='{{action.deadline_date|date:"Y-m-d"}}' required>
                    </div>
                </div>
                <div class="form_fields">
                    <div class="action_form_title">
                        <legend class="label">Issue</legend>
                        <input type="text" placeholder="Text" id="issue_name" value="{{action.issue_name}}" required>
                    </div>
                </div>
                <div class="form_fields">
                    <div class="action_form_action">
                        <legend class="label">Action</legend>
                        <input type="text" placeholder="Text" id="action_text" value="{{action.action_text}}" required>
                    </div>
                </div>
                <div class="form_fields">
                    <div class="action_form_solution">
                        <legend class="label">Solution</legend>
                        <input type="text" placeholder="Text" id="solution_text" value="{{action.solution_text}}">
                    </div>
                </div>
                <div class="form_fields">
                    <fieldset class="action_form_perfromer">
                        <span class="label">Performers</span>
                        <div class="checkbox-dropdown">
                            <ul class="checkbox-dropdown-list">
                                {% for user in user_profile_list %}
                                    <li>
                                        <input type="checkbox" id="{{user.pk}}" value="{{user.pk}}" name="action_editing_assigned_user"
                                        {% if user in action.assigned_user.all%}
                                            checked
                                        {% endif%}
                                        >
                                        <label for="{{user.pk}}">
                                            <img alt="{{user.first_name}} {{user.last_name}}"
                                                    title="{{user.first_name}} {{user.last_name}}"  
                                                    src="{{user.user_image.url}}">
                                            <span class="performer_name">{{user.first_name}}</span>
                                            <span class="performer_surname">{{user.last_name}}</span>
                                        </label>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="user_images">

                        </div>
                    </fieldset>
                </div>
                <div class="form_fields edit_buttons">
                    <button class="button confirm" type="submit">Confirm</button>
                    <button style="display: none;" class="button button-loader">{% include 'button-loader.html' %}</button>
                    <button  href="#" onclick="closeEditingForm()" class="cancel" type="reset">Back to actions</button>
                </div>
            </form>
        </div>
    </div>
    <script src="{% static '/js/action_form.js' %}"></script>      
    <script>
        $("#all_users").click(function () {
            var checkboxes = document.getElementsByName('assigned_user');
            // loop over them all
            if (checkboxes[0].checked == false){
                for (var i=0; i<checkboxes.length; i++) {
                    checkboxes[i].checked = false;
                }
            }
            else{
                for (var i=0; i<checkboxes.length; i++) {
                    checkboxes[i].checked = true;
                }
            }
        });
        $(".show-more").click(function () {
            var elements = $(".hiden");
            $.each(elements, function (index, tr) {
                $(this).css("display", "table-row");
            });
            $(this).css("display", "none");
            $(".show-less").css("display", "block");
        });
        $(".show-less").click(function () {
            var elements = $(".hiden");
            $.each(elements, function (index, tr) {
                $(this).css("display", "none");
            });
            $(this).css("display", "none");
            $(".show-more").css("display", "block");
        });

        $(".checkbox-dropdown").click(function () {
            $(this).toggleClass("is-active");
            // $(".checkbox-dropdown").toggleClass("is-active");
        });

        $(".checkbox-dropdown ul").click(function(e) {
            e.stopPropagation();
        });
        function getCheckedBoxes(chkboxName) {
            var checkboxes = document.getElementsByName(chkboxName);
            var checkboxesChecked = [];
            // loop over them all
            for (var i=0; i<checkboxes.length; i++) {
                // And stick the checked ones onto an array...
                if (checkboxes[i].checked) {
                    if (checkboxes[i].value != "all"){
                        checkboxesChecked.push(checkboxes[i].value);
                    }
                }
            }
            // Return the array if it is non-empty, or null
            return checkboxesChecked.length > 0 ? checkboxesChecked : null;
        }

        function openForm() {
            var element = document.getElementById("popup");
            element.classList.add("show");
            document.body.style.overflowY = "hidden";
            $('.confirm').show();
        }
        function closeForm() {
            var element = document.getElementById("popup");
            element.classList.remove("show");
            document.body.style.overflowY = "scroll";
            $(".checkbox-dropdown").toggleClass("is-active");
        }
        function closeEditingForm() {
            var element = document.getElementById("edit-popup");
            element.classList.remove("show");
            document.body.style.overflowY = "scroll";
            $(".checkbox-dropdown").toggleClass("is-active");
        }
        $("input[type='checkbox'][name='assigned_user']").click(function () {
            if ($("input[type='checkbox']#all_users:checked") && $(this).attr("id")!='all_users'){
                $("input[type='checkbox']#all_users").prop('checked',false);
            }
        });        
        $(document).on('submit', '#action_editing_form',function(e){
            e.preventDefault();
            $('.confirm').hide();
            $('.button-loader').show();

            var date = new Date($(this).children('.form_fields').children('.deadline').children('input').val());
            var day = date.getDate();
            var month = date.getMonth() + 1;
            var year = date.getFullYear();

            deadline_date = [year, month, day ].join('-');           
            
            let checkboxes= $(this).find("input[type='checkbox']")
            var checkboxesChecked = [];
            var checkboxesUnchecked = [];

            for (var i=0; i<checkboxes.length; i++) {
                // And stick the checked ones onto an array...
                if (checkboxes[i].checked == false) {
                    if (checkboxes[i].id != 'all_users'){
                        checkboxesUnchecked.push(checkboxes[i].value);
                    }
                } else
                if (checkboxes[i].checked == true){
                    if (checkboxes[i].id != 'all_users'){
                        checkboxesChecked.push(checkboxes[i].value);
                    }  
                }
            }
            let unassigned_user = checkboxesUnchecked.join();
            let assigned_user = "";

            if(checkboxesChecked.length === 0){
                alert("Please select assigned user");
                $('.confirm').show();
                $('.button-loader').hide();
                return false;
            } 
            else {
                assigned_user = checkboxesChecked.join();
            }

            $.ajax({
                type:'POST',
                url:'{% url "actions:actions_history" %}',
                data:{
                    action_pk: $(this).attr('value'),
                    selected_status: $(this).find("input[type='radio'][name='status']:checked").val(),
                    deadline_date: deadline_date,
                    issue_name: $(this).children('.form_fields').children('.action_form_title').children('input').val(),
                    action_text: $(this).children('.form_fields').children('.action_form_action').children('input').val(),
                    solution_text: $(this).children('.form_fields').children('.action_form_solution').children('input').val(),
                    assigned_user: assigned_user,
                    unassigned_user: unassigned_user,

                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                    action: 'edit'
                },
                success:function(json){
                    // $('.actions_table').html('');
                    console.log(json)
                    $('.actions_table').html(json);
                    closeEditingForm();
                    $('.confirm').show();
                    $('.button-loader').hide();
                    $(".show-less").css("display", "none");
                    $(".show-more").css("display", "block");
                    $(".checkbox-dropdown").toggleClass("is-active");
                },
                error : function(xhr,errmsg,err) {
                    $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                        " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        });
    </script>
{% endblock content %}

actions/templates/all_actions.html
{% load static %}
    <tr class="headling">
        <th>Date</th>
        <th>Issue</th>
        <th>Action</th>
        <th>Solution</th>
        <!-- <th class="filtering">Who?</th>
        <th class="filtering">When?</th> -->
        <th>Who?</th>
        <th>When?</th>
        <th>Status</th>
    </tr>
    {% for action in all_actions %}
        <tr id="action_content">
            <td class="date">{{action.creation_date|date:"d/M"}}</td>
            <td class="action_title">
                <a href="#" class="title_click" id="{{action.pk}}">{{action.issue_name}}</a>
            </td>
            <td class="action_text">{{action.action_text}}</td>
            <td class="action_solution">{{action.solution_text}}</td>
            <td class="members" id="members_for_{{action.pk}}">
                {% if action.assigned_user.all.count == group_members %}
                    <div class="img-block all">
                        <img src="{% static '/img/all_users.svg' %}"" alt="All users">
                    </div>
                {% else %}
                    <div class="img-block">
                        {% for user in action.assigned_user.all %}
                            <img alt="{{user.first_name}} {{user.last_name}}" 
                                title="{{user.first_name}} {{user.last_name}}"
                                src="{{user.user_image.url}}"> 
                        {% endfor %}
                    </div>
                {% endif %}
            </td>
            <td class="date">{{action.deadline_date|date:"d/M"}}</td>
            <td class="status" id="{{action.pk}}">
                {% if action.action_status == 'draft' %}
                    <img alt="In progress" title="In progress" id="1" src="{% static '/img/in_progress.svg' %}">
                {% elif action.action_status == 'completed' %}
                    <img alt="Completed" title="Completed" id="2" src="{% static '/img/done.svg' %}">
                {% else %}
                    <img alt="Canceled" title="Canceled" id="3" src="{% static '/img/cancel.svg' %}">
                {% endif %}
            </td>
        </tr>
    {% endfor %}
<script>
    $('.title_click, .status').on("click", function(e) {
        e.preventDefault();
        $('.confirm').show();
        $('.button-loader').hide();
        // get the action id
        var action_pk = $(this).attr("id");
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: '{% url "actions:action_main" %}',
            data: {
                action_pk: action_pk,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'get_data'
            },
            success: function (response) {
                var form = $("form#action_editing_form");
                $(form)[0].reset();
                $(form).attr("value", response.action_pk);
                $(form).children('.checkboxes').children('.'+response.action_status+'').children('input').prop('checked', true);
                $(form).children('.form_fields').children('.deadline').children('input').attr("value",response.deadline_date);
                $(form).children('.form_fields').children('.action_form_title').children('input').attr("value",response.issue_name);
                $(form).children('.form_fields').children('.action_form_action').children('input').attr("value",response.action_text);
                $(form).children('.form_fields').children('.action_form_solution').children('input').attr("value",response.solution_text);
                var assigned_user_list = response.assigned_users.split(',');
                console.log(assigned_user_list);
                $(form).find("input[type='checkbox']").prop('checked', false);
                var checkbox_list = $(form).find("input[type='checkbox']")
                console.log(checkbox_list);
                // Market assigned users ass selected in form
                for (let i=0; i<assigned_user_list.length;i++){
                    console.log("User ID:"+ assigned_user_list[i]);
                    // form.find("input[type='checkbox']#"+assigned_user_list[id]+"").prop('checked', true);
                    for (let j=0; j<$(checkbox_list).length;j++){
                        if ($(checkbox_list[j]).attr("value") == assigned_user_list[i]){
                            $(checkbox_list[j]).prop('checked', true);
                            console.log($(checkbox_list[j]).attr("value"));
                        }    
                    }  
                }
                
                var element = document.getElementById("edit-popup");
                element.classList.add("show");
                document.body.style.overflowY = "hidden";
            },
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        })
    })
</script>