authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from src import settings
from django.urls import path
from .views import edit, dashboard, wor_dates_generator, register, wor_calendar_generation, agenda, settings
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'authapp'

urlpatterns = [
    path('accounts/register/', register, name='register'),
    path('accounts/edit/', edit, name='edit'),
    path('accounts/profile/', dashboard, name='dashboard'),
    path('accounts/settings/', settings, name='settings'),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', agenda, name='agenda'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('generate/', wor_calendar_generation, name='calendar_generate'),
    path('wor-dates-generator/', wor_dates_generator, name='wor_dates_generator'),
    path('logout/', LogoutView.as_view(template_name='authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),
]

she/urls.py
from django.urls import path
from she.views import she_main


urlpatterns = [
    path('', she_main, name='she_main'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new



from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
    path('actions/', include(('actions.urls', 'actions'), namespace='actions')),
    path('attendance/', include(('attendance.urls', 'recognition_page'), namespace='attendance')),
    path('improvements/', include(('improvements.urls', 'improvements'), namespace='improvements')),
    path('notice-board/', include(('notice_board.urls', 'notice_board'), namespace='notice-board')),
    path('recognitions/', include(('recognitions.urls', 'recognition_page'), namespace='recognitions')),
    path('she/', include(('she.urls', 'she_page'), namespace='she')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import datetime  
from django.db import models
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import AbstractUser, Group
# Create your models here.


class UserModel(AbstractUser):
    id = models.AutoField(primary_key=True)
    objects = UserManager()
    user_image = models.ImageField(blank=False, upload_to="profile_image/", default='default_image/default_user_image.png',
                                   verbose_name="Profile image")
    user_position = models.CharField(blank=True, max_length=255, verbose_name="User position")
    user_about = models.TextField(blank=True, verbose_name="About you")

    class Meta:
        ordering = ['first_name']

class GroupAdmin(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name="Group admin")
    group = models.ForeignKey(Group, blank=True, default="1", on_delete=models.CASCADE, verbose_name="Group")
    group_time_zone = models.IntegerField(default="2", verbose_name="Time zone")

class Meta:
    permission =[( "edit_facilitators", "Can edit facilitators",)]

authapp/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserModel
from django.contrib.auth.forms import PasswordResetForm
from django.forms.widgets import ClearableFileInput

class ImageWidget(ClearableFileInput):
    template_name = 'authapp/image_widget.html'

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['image_url'] = value.url if value else ''
        return context

    def value_from_datadict(self, data, files, name):
        upload = super().value_from_datadict(data, files, name)
        if data.get(name + '-clear') == 'on':
            return False
        return upload

class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email', 'user_image', 'user_position', 'user_about')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    user_about = forms.CharField(widget=forms.Textarea(attrs={'spellcheck': 'true'}), max_length=200)
    user_image = forms.ImageField(widget=ImageWidget, required=False)
    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'email', 'user_image', 'user_position', 'user_about')

    def clean_user_about(self):
        user_about = self.cleaned_data['user_about']
        if len(user_about) > 200:
            raise forms.ValidationError("User about cannot be more than 200 characters")
        return user_about

authapp/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import UserRegistration, UserEditForm
from .models import UserModel, GroupAdmin
from recognitions.models import RecognitionManagerModel
from attendance.models import AttendanceManagerModel, WOR_date, WeekAttendanceRoleManager
from actions.models import ActionTaskManagerModel
import datetime
from datetime import timedelta
import time
from django.core.cache import cache

# Create your views here.
def user_present(user_id):
    date = datetime.datetime.now()
    user_last_login = UserModel.objects.get(pk = user_id).last_login + timedelta(hours = 2)
    user_last_login_date = user_last_login.strftime('%y-%m-%d')
    user_last_login_time = user_last_login.strftime('%H')
    current_date = date.strftime('%y-%m-%d')
    current_time = date.strftime('%H')

    if (user_last_login_date == current_date and int(current_time)- int(user_last_login_time) <2):
        return True
    else:
        return False
@login_required(login_url='/login/')   
def wor_dates_generator(request):
    today = datetime.datetime.today()
    date = today
    # Generating Weeks
    for i in range(52):
        current_week = date.strftime("%V")
        # Calculate the date for the Monday of the current week
        monday = date - timedelta(days=date.weekday())
        # Calculate the date for the Sunday of the current week
        sunday = monday + timedelta(days=6)

        if current_week[0] == "0":
            current_week = int(current_week) % 10
        else:
            current_week = current_week 
        WOR_date.objects.get_or_create(
            start_date = monday,
            end_date = sunday,
            week_number = current_week,
        )
        date = date + datetime.timedelta(days=7)
    return redirect('/accounts/settings/')

@login_required(login_url='/login/')
def dashboard(request):
    profile_information = UserModel.objects.get(id=request.user.pk)
    recognition = RecognitionManagerModel.objects.get(user_profile = request.user)
    actions_list = ActionTaskManagerModel.objects.filter(
        action_group =  UserModel.objects.get(id = request.user.id).groups.first(),
        assigned_user = profile_information,
        action_status = "draft" 
    )
    users_list =  UserModel.objects.filter(groups =  UserModel.objects.get(id = request.user.id).groups.first())
    return render(request, 'authapp/dashboard.html', { 
        'profile_information': profile_information,
        'recognitions': recognition, 
        'actions': actions_list,
        'users': users_list,
        })
@login_required(login_url='/login/')
def agenda(request):
    user = UserModel.objects.get(id=request.user.id)
    group = user.groups.first()
    current_week = datetime.datetime.now().strftime("%V")
    week_roles = WeekAttendanceRoleManager.objects.select_related('users_group', 'week_id').filter(
        users_group=group,
        week_id__week_number=current_week
    )
    current_week_roles = WeekAttendanceRoleManager.objects.filter(
        users_group = UserModel.objects.get(id = request.user.id).groups.first(), 
        week_id = WOR_date.objects.get(week_number = current_week)
    )

    try:
        this_group_admin = GroupAdmin.objects.get(group=group).admin
    except GroupAdmin.DoesNotExist:
        this_group_admin = ""

    next_week_number = str(int(current_week) + 1)
    next_week_roles = WeekAttendanceRoleManager.objects.select_related('users_group', 'week_id').filter(
        users_group=group,
        week_id__week_number=next_week_number
    )

    message = ""
    if request.POST.get('action') == 'change_leader':
        if user_present(week_roles.wor_leader.pk):
            message = "wor_leader"
        elif user_present(week_roles.wor_engager.pk) and request.user == week_roles.wor_engager:
            next_week_roles.wor_leader = week_roles.wor_leader
            next_week_roles.save()
            week_roles.wor_leader = week_roles.wor_engager
            week_roles.save()
            message = "wor_engager"
        else:
            this_week_leader = week_roles.wor_leader
            week_roles.wor_leader = request.user
            week_roles_list = WeekAttendanceRoleManager.objects.filter(users_group=group).filter(
                week_id__week_number__gt=current_week, wor_leader=request.user
            )
            for week in week_roles_list:
                week.wor_leader = this_week_leader
                week.save()
                break
            week_roles.save()

        try:
            wor_leader_present = user_present(current_week_roles[0].wor_leader.pk)
            wor_engager_present = user_present(current_week_roles[0].wor_engager.pk)
        except:
            wor_leader_present = False
            wor_engager_present = False
    
        context = {
            "wor_leader_present": wor_leader_present,
            "wor_engager_present": wor_engager_present,
            "message": message,
            "week_role": week_roles,
            "current_week_roles": current_week_roles,
            "next_week_role": next_week_roles
        }
        return render(request, 'account/agenda-facilitators.html', context=context)
    
    try:
        wor_leader_present = user_present(current_week_roles[0].wor_leader.pk)
        wor_engager_present = user_present(current_week_roles[0].wor_engager.pk)
    except:
        wor_leader_present = False
        wor_engager_present = False

    context = {
        "wor_leader_present": wor_leader_present,
        "wor_engager_present": wor_engager_present,
        "message": message,
        "week_roles": week_roles,
        "current_week_roles": current_week_roles,
        "next_week_roles": next_week_roles,
    }
    return render(request, 'account/agenda.html', context=context)

@login_required(login_url='/login/')
def wor_calendar_generation(request):
    current_user = UserModel.objects.get(id=request.user.id)
    user_group = current_user.groups.first()
    current_group_user_list = UserModel.objects.filter(groups=user_group)
    print(current_group_user_list)
    ready_selected = current_group_user_list[0].id

    # Collect updates in a list
    updates = []

    for week in WOR_date.objects.all():
        for j in range(current_group_user_list.count()):
            if current_group_user_list[j].id == ready_selected:
                week_id=WOR_date.objects.get(week_number=week.week_number)
                if current_group_user_list[j] == current_group_user_list[current_group_user_list.count() - 1]:
                    print("List breaks on "+ str(current_group_user_list[j]))
                    try:
                        WeekAttendanceRole = WeekAttendanceRoleManager.objects.get(
                            week_id=week_id,
                            users_group=user_group
                        )
                        WeekAttendanceRole.wor_leader = current_group_user_list[j]
                        WeekAttendanceRole.wor_engager = current_group_user_list[0]
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[0].id
                        break
                    except WeekAttendanceRoleManager.DoesNotExist:
                        WeekAttendanceRole = WeekAttendanceRoleManager(
                            week_id=week_id,
                            users_group=user_group,
                            wor_leader=current_group_user_list[j],
                            wor_engager=current_group_user_list[0],
                        )
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[0].id
                        break
                else:
                    print("List continue with user "+ str(current_group_user_list[j]))
                    try:
                        WeekAttendanceRole = WeekAttendanceRoleManager.objects.get(
                            week_id=week_id,
                            users_group=user_group
                        )
                        WeekAttendanceRole.wor_leader = current_group_user_list[j]
                        WeekAttendanceRole.wor_engager = current_group_user_list[j + 1]
                        print("WeekAttendanceRole.wor_engager"+ str(ready_selected))
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[j + 1].id

                        break
                    except WeekAttendanceRoleManager.DoesNotExist:
                        WeekAttendanceRole = WeekAttendanceRoleManager(
                            week_id=week_id,
                            users_group=user_group,
                            wor_leader=current_group_user_list[j],
                            wor_engager=current_group_user_list[j + 1],
                        )
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[j + 1].id
                        break

    # Bulk update the changes
    for update in updates:
        update.save()

    return redirect('/accounts/settings/')

@login_required(login_url='/login/')
def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST, request.FILES)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            time.sleep(1)

            new_user.groups.add(UserModel.objects.get(id = request.user.id).groups.first())
            new_user.last_login = datetime.datetime.now() - timedelta(hours = 8)
            new_user.save()

            RecognitionManagerModel.objects.get_or_create(
                user_profile = UserModel.objects.get(id = new_user.id)

authapp/templates/authapp/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block page-title %} | Profile Settings{% endblock page-title %}
{% block title %}Dashboard{% endblock title %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/account.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/profile.css' %}">
{% endblock styles %}
{% block content %}
{% if not profile_information.groups.first %}
  <div class="form_container">
      <div class="message_form">
          <h3 class="form-title">Access to the specific group board needs to be gained!</h3>
          <div class="message">
              <p>Dear {{profile_information.first_name}} {{profile_information.last_name}}, </p>
              <p>Currently, you do not have access to any group that is essential for collaboration and information sharing within the website. 
                 We kindly request you to contact your line manager to be added to the relevant group.</p>
              <p>Kindly regards, development team.</p>
              <p style="text-align: center;"><a href="/logout">Logout</a></p>
          </div>
      </div>
  </div>
  <style>
    .form_container{
        display: flex;
        position: fixed;
        visibility: visible;
        z-index: 2;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
        background-color: rgba(22, 22, 22, 0.5); /* complimenting your modal colors */
    }
    .message_form{
        padding: 10px;
        display: block;
        width: 50%;
        /* #FFFFFF */
        background: #FFFFFF;
        /* Drop Shadow */
        box-shadow: 0px 6px 18px rgba(0, 0, 0, 0.06);
        border-radius: 4px;
    }
    .message_form .form-title {
        text-align: left;
        color: green;
        font-size: 15px;
        border-bottom: 2px solid green;
        margin: 0 12px 12px 12px;
        padding: 12px 0px;
        font-weight: 700;
    }
    .message_form .message{
        padding: 12px;
        font-weight: 400;
    }
  </style>
{% endif %}
<div class="headling">
    <div class="btns">
      <a class="edit_profile" href="{% url 'authapp:edit' %}">Edit your profile</a>
      <a class="password_change" href="{% url 'authapp:password_change' %}">Change your password</a>
    </div>
    <h2 class="page-title">Settings</h2>
    <div class="content_tabs">
        <a href="#" class="active">Account setup</a>
        <a href="{% url 'authapp:settings' %}">Facilitator settings</a>
    </div>
</div>
<div class="user_about">
  <div class="user_visuals">
    <div class="user_image">
      <img src="{{profile_information.user_image.url}}" alt="">
    </div>
    <div class="user_recognitions">
      <div class="member_stars">
        <div class="star initiative">
            <img src="{% static '/img/star.svg' %}" name="initiative" id="{{recognition.id}}" class="star_click">
            <span name="initiative_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.initiative_value}}</span>
        </div>
        <div class="star ube">
            <img src="{% static '/img/star.svg' %}" name="ube" id="{{recognition.id}}" alt="" class="star_click">
            <span name="ube_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.understand_value}}</span>
        </div>
        <div class="star pwyp">
            <img src="{% static '/img/star.svg' %}" name="pwyp" id="{{recognition.id}}" alt="" class="star_click">
            <span name="pwyp_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.practice_value}}</span>
        </div>
        <div class="star resut_focus">
            <img src="{% static '/img/star.svg' %}" name="resut_focus" id="{{recognition.id}}" alt="" class="star_click">
            <span name="resut_focus_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.result_focus_value}}</span>
        </div>
        <div class="star know_yourself">
            <img src="{% static '/img/star.svg' %}" name="know_yourself" id="{{recognition.id}}" alt="" class="star_click">
            <span name="know_yourself_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.know_yourself_value}}</span>
        </div>
        <div class="star proactive_cooperation">
            <img src="{% static '/img/star.svg' %}" name="proactive_cooperation" id="{{recognition.id}}" alt="" class="star_click">
            <span name="proactive_cooperation_{{recognition.id}}" id="{{recognition.id}}">{{recognitions.cooperation_value}}</span>
        </div>
      </div>
      <div class="total_stars">
          <span>Total:</span>
          <span name="total_stars_{{recognition.id}}"> {{recognitions.total_stars}}</span>
      </div>
    </div>
  </div>
  <div class="user_profile_description">
    <div class="user_name">
      <p class="label">First and Last Name</p>
      <p>{{profile_information.first_name}} {{profile_information.last_name}}</p>
    </div>
    <div class="user_emal">
      <p class="label">E-mail</p>
      <p>{{profile_information.email}}</p>
    </div>
    <div class="user_position">
      <p class="label">Position</p>
      <p>{{profile_information.user_position}} </p>
    </div>  
    <div class="user_description">
        <p class="label">My description (max 130 symbols)</p>
        <p>{{profile_information.user_about}}</p>
    </div>
  </div>
</div>
<div class="user_actions">
  <p class="label">Active actions:</p>
  <div class="actions_list">
    <!-- For loop one block -->
    {% if actions %}
      {% for action in actions %}
        {% if request.user in action.assigned_user.all %}
          <div class="task-content">
            <div class="date-status">
                <span class="{{action.action_status}}-status">In progress</span> 
                <span class="task-date">{{action.deadline_date|date:"d/M"}}</span>
            </div>
            <div class="task-text">
                <p class="topic">{{action.issue_name}}</p>
                <!-- <p class="task-description"> {{action.action_text}}</p>
                <p class="task-description"> {{action.solution_text}}</p> -->
            </div>
            <!-- <div class="members">
              {% if action.assigned_user.all.count == group_members %}
                    <div class="img-block all">
                        <img src="{% static '/img/all_users.svg' %}"" alt="All users">
                    </div>
                {% else %}
                    <div class="img-block">
                        {% for user in action.assigned_user.all %}
                            <img alt="{{user.first_name}} {{user.last_name}}" 
                                title="{{user.first_name}} {{user.last_name}}"
                                src="{{user.user_image.url}}"> 
                        {% endfor %}
                    </div>
                {% endif %}
            </div> -->
          </div>
        {% endif %}
      {% endfor %}
    {% else %} 
      <p class="label" style="display: block; margin: auto;padding: 2%;">No active actions!</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

authapp/templates/authapp/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}

<style>
    form .form-group label {
        /* font-size: 16px; */
        padding: 10px 0 10px 0;
    }

    p {
        font-size: 16px;
    }

    .form-control {
        color: #808080;
    }

    input[text] {
        color: #808080;
    }

    .form-group:nth-child(5) {
        font-size: 12px;
        color: #515151;
    }

    .form-group:nth-child(5) a {
        font-size: 12px;
        color: #515151;
    }

    input[type=file]::file-selector-button {
        background-color: #fff;
        color: #515151;
        border: 1px solid #515151;
        padding: 5.5px 18px;
        border-radius: 4px;
        font-weight: 400;
        font-size: 10px;
        margin-top: 10px;
    }

    #id_user_image {
        min-width: 400px;
    }

    .cancel {
        border: 1px solid #D64123;
        color: #D64123;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
        margin-right: 5%;
    }

    .btn-primary:active:focus {
        box-shadow: none;
    }

    .cancel:focus,
    .cancel,
    .cancel:active {
        border: 1px solid #D64123;
        color: #D64123;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
        margin-right: 5%;
    }

    .cancel:hover {
        border: 1px solid #D64123;
        color: #fff;
        background-color: #D64123;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        margin-right: 5%;
    }

    button[type=submit] {
        border: 1px solid #2E8025;
        color: #2E8025;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
    }

    button[type=submit]:focus,
    button[type=submit]:active {
        border: 1px solid #2E8025;
        color: #fff;
        background-color: #2E8025;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
    }

    button[type=submit]:hover {
        border: 1px solid #2E8025;
        color: #fff;
        background-color: #2E8025;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
    }

    form {
        padding-bottom: 100px;
    }

    textarea.form-control {
        resize: none;
        height: 80px;
    }

    .btn-primary {
        color: #fff;
        background-color: #63513d;
        border-color: #63513d;
    }
</style>
<h2 class="page-title">Edit your account</h2>
<p>You can edit your account using the follow form:</p>
<form action="" method="post" style="width: 50%;" class="form" accept-charset="utf-8" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="submit">Submit</button>
    <a type="button" href="{% url 'authapp:dashboard' %}" class="cancel" style="padding: 11px 24px;">Cancel</a>
    {% endbuttons %}
</form>
{% endblock content %}

authapp/templates/authapp/image_widget.html
<style>
  .image_change{
    display: flex;
    flex-direction: column;
  }  
</style>
<div class="image_change">
    {% if widget.is_initial %}
        <img src="{{ widget.value.url }}" alt="{{ widget.value.name }}" width="100">
    {% endif %}
    {{ widget.input }} </br>
    {% if widget.is_initial %}
        <input type="file" name="{{ widget.name }}" id="{{ widget.id_for_label }}-new">
    {% endif %}
</div>

authapp/templates/authapp/logged_out.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'authapp:login' %}">log-in again</a>.
</p>
{% endblock %}

authapp/templates/authapp/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<style>

    .content-block {
        min-height: 633px;
    }

    form .form-group label {
        padding: 10px 0 10px 0;
    }

    p {
        font-size: 16px;
    }

    .form-control {
        color: #808080;
    }

    input[text] {
        color: #808080;
    }

    .cancel {
        border: 1px solid #D64123;
        color: #D64123;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
        margin-right: 5%;
    }

    .btn-primary:active:focus {
        box-shadow: none;
    }

    .cancel:focus,
    .cancel,
    .cancel:active {
        border: 1px solid #D64123;
        color: #D64123;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
        margin-right: 5%;
    }

    .cancel:hover {
        border: 1px solid #D64123;
        color: #fff;
        background-color: #D64123;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        margin-right: 5%;
    }

    button[type=submit] {
        border: 1px solid #2E8025;
        color: #2E8025;
        background-color: #fff;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
    }

    button[type=submit]:focus,
    button[type=submit]:active {
        border: 1px solid #2E8025;
        color: #fff;
        background-color: #2E8025;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
        box-shadow: none;
    }

    button[type=submit]:hover {
        border: 1px solid #2E8025;
        color: #fff;
        background-color: #2E8025;
        float: right;
        margin: 50px 0px;
        padding: 8px 24px;
        line-height: 1rem;
    }

    .page-title {
        color: green;
        font-size: 15px;
        border-bottom: 2px solid green;
        padding-bottom: 25px;
        font-weight: 700;
        margin-bottom: 16px;
    }
</style>
<div style="display: block; margin: 0 auto;">
    <h2 class="page-title">Change Your Password</h2>
    <p>Use the form below to change your Password</p>
    <form action="" 
        method="post" 
        class="form"
        style="width: 50%;"
    >
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <br />
        <button type="submit" class="submit">Submit</button>
        <a type="button" href="{% url 'authapp:dashboard' %}" class="cancel" style="padding: 11px 24px;">Cancel</a>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

authapp/templates/authapp/password_reset_email.html
{% autoescape off %}
Hello, {{email}}

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'authapp:password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
The {{ domain }} Website Team

{% endautoescape %}