actions/urls.py
from django.conf.urls.static import static
from src import settings
from django.urls import path, include
from .views import actions, actions_history

urlpatterns = [
    path('', actions, name='action_main'),
    path('history/', actions_history, name='actions_history'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
from django.urls import path
from attendance.views import attendance, attendance_history


urlpatterns = [
    path('', attendance, name='attendance_page'),
    path('history/', attendance_history, name='attendance_history'),
]

authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from src import settings
from django.urls import path
from .views import edit, dashboard, wor_dates_generator, register, wor_calendar_generation, agenda, settings
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'authapp'

urlpatterns = [
    path('accounts/register/', register, name='register'),
    path('accounts/edit/', edit, name='edit'),
    path('accounts/profile/', dashboard, name='dashboard'),
    path('accounts/settings/', settings, name='settings'),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', agenda, name='agenda'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('generate/', wor_calendar_generation, name='calendar_generate'),
    path('wor-dates-generator/', wor_dates_generator, name='wor_dates_generator'),
    path('logout/', LogoutView.as_view(template_name='authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),
]

improvements/urls.py
from django.urls import path
from .views import improvements, improvement_edit, change_status

urlpatterns = [
    path('', improvements, name='improvements_main'),
    path('edit/<int:pk>', improvement_edit, name='improvement_edit'),
    path('status/<int:pk>', change_status, name='change_status'),
]

recognitions/urls.py
from django.urls import path

from .views import recognition_page, recognition_update

from src import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', recognition_page, name='recognition_page'),
    path('update/', recognition_update, name='recognition_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she/urls.py
from django.urls import path
from she.views import she_main


urlpatterns = [
    path('', she_main, name='she_main'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new



from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
    path('actions/', include(('actions.urls', 'actions'), namespace='actions')),
    path('attendance/', include(('attendance.urls', 'recognition_page'), namespace='attendance')),
    path('improvements/', include(('improvements.urls', 'improvements'), namespace='improvements')),
    path('notice-board/', include(('notice_board.urls', 'notice_board'), namespace='notice-board')),
    path('recognitions/', include(('recognitions.urls', 'recognition_page'), namespace='recognitions')),
    path('she/', include(('she.urls', 'she_page'), namespace='she')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserModel
from django.contrib.auth.forms import PasswordResetForm
from django.forms.widgets import ClearableFileInput

class ImageWidget(ClearableFileInput):
    template_name = 'authapp/image_widget.html'

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['image_url'] = value.url if value else ''
        return context

    def value_from_datadict(self, data, files, name):
        upload = super().value_from_datadict(data, files, name)
        if data.get(name + '-clear') == 'on':
            return False
        return upload

class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email', 'user_image', 'user_position', 'user_about')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    user_about = forms.CharField(widget=forms.Textarea(attrs={'spellcheck': 'true'}), max_length=200)
    user_image = forms.ImageField(widget=ImageWidget, required=False)
    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'email', 'user_image', 'user_position', 'user_about')

    def clean_user_about(self):
        user_about = self.cleaned_data['user_about']
        if len(user_about) > 200:
            raise forms.ValidationError("User about cannot be more than 200 characters")
        return user_about

authapp/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import UserRegistration, UserEditForm
from .models import UserModel, GroupAdmin
from recognitions.models import RecognitionManagerModel
from attendance.models import AttendanceManagerModel, WOR_date, WeekAttendanceRoleManager
from actions.models import ActionTaskManagerModel
import datetime
from datetime import timedelta
import time
from django.core.cache import cache

# Create your views here.
def user_present(user_id):
    date = datetime.datetime.now()
    user_last_login = UserModel.objects.get(pk = user_id).last_login + timedelta(hours = 2)
    user_last_login_date = user_last_login.strftime('%y-%m-%d')
    user_last_login_time = user_last_login.strftime('%H')
    current_date = date.strftime('%y-%m-%d')
    current_time = date.strftime('%H')

    if (user_last_login_date == current_date and int(current_time)- int(user_last_login_time) <2):
        return True
    else:
        return False
@login_required(login_url='/login/')   
def wor_dates_generator(request):
    today = datetime.datetime.today()
    date = today
    # Generating Weeks
    for i in range(52):
        current_week = date.strftime("%V")
        # Calculate the date for the Monday of the current week
        monday = date - timedelta(days=date.weekday())
        # Calculate the date for the Sunday of the current week
        sunday = monday + timedelta(days=6)

        if current_week[0] == "0":
            current_week = int(current_week) % 10
        else:
            current_week = current_week 
        WOR_date.objects.get_or_create(
            start_date = monday,
            end_date = sunday,
            week_number = current_week,
        )
        date = date + datetime.timedelta(days=7)
    return redirect('/accounts/settings/')

@login_required(login_url='/login/')
def dashboard(request):
    profile_information = UserModel.objects.get(id=request.user.pk)
    recognition = RecognitionManagerModel.objects.get(user_profile = request.user)
    actions_list = ActionTaskManagerModel.objects.filter(
        action_group =  UserModel.objects.get(id = request.user.id).groups.first(),
        assigned_user = profile_information,
        action_status = "draft" 
    )
    users_list =  UserModel.objects.filter(groups =  UserModel.objects.get(id = request.user.id).groups.first())
    return render(request, 'authapp/dashboard.html', { 
        'profile_information': profile_information,
        'recognitions': recognition, 
        'actions': actions_list,
        'users': users_list,
        })
@login_required(login_url='/login/')
def agenda(request):
    user = UserModel.objects.get(id=request.user.id)
    group = user.groups.first()
    current_week = datetime.datetime.now().strftime("%V")
    week_roles = WeekAttendanceRoleManager.objects.select_related('users_group', 'week_id').filter(
        users_group=group,
        week_id__week_number=current_week
    )
    current_week_roles = WeekAttendanceRoleManager.objects.filter(
        users_group = UserModel.objects.get(id = request.user.id).groups.first(), 
        week_id = WOR_date.objects.get(week_number = current_week)
    )

    try:
        this_group_admin = GroupAdmin.objects.get(group=group).admin
    except GroupAdmin.DoesNotExist:
        this_group_admin = ""

    next_week_number = str(int(current_week) + 1)
    next_week_roles = WeekAttendanceRoleManager.objects.select_related('users_group', 'week_id').filter(
        users_group=group,
        week_id__week_number=next_week_number
    )

    message = ""
    if request.POST.get('action') == 'change_leader':
        if user_present(week_roles.wor_leader.pk):
            message = "wor_leader"
        elif user_present(week_roles.wor_engager.pk) and request.user == week_roles.wor_engager:
            next_week_roles.wor_leader = week_roles.wor_leader
            next_week_roles.save()
            week_roles.wor_leader = week_roles.wor_engager
            week_roles.save()
            message = "wor_engager"
        else:
            this_week_leader = week_roles.wor_leader
            week_roles.wor_leader = request.user
            week_roles_list = WeekAttendanceRoleManager.objects.filter(users_group=group).filter(
                week_id__week_number__gt=current_week, wor_leader=request.user
            )
            for week in week_roles_list:
                week.wor_leader = this_week_leader
                week.save()
                break
            week_roles.save()

        try:
            wor_leader_present = user_present(current_week_roles[0].wor_leader.pk)
            wor_engager_present = user_present(current_week_roles[0].wor_engager.pk)
        except:
            wor_leader_present = False
            wor_engager_present = False
    
        context = {
            "wor_leader_present": wor_leader_present,
            "wor_engager_present": wor_engager_present,
            "message": message,
            "week_role": week_roles,
            "current_week_roles": current_week_roles,
            "next_week_role": next_week_roles
        }
        return render(request, 'account/agenda-facilitators.html', context=context)
    
    try:
        wor_leader_present = user_present(current_week_roles[0].wor_leader.pk)
        wor_engager_present = user_present(current_week_roles[0].wor_engager.pk)
    except:
        wor_leader_present = False
        wor_engager_present = False

    context = {
        "wor_leader_present": wor_leader_present,
        "wor_engager_present": wor_engager_present,
        "message": message,
        "week_roles": week_roles,
        "current_week_roles": current_week_roles,
        "next_week_roles": next_week_roles,
    }
    return render(request, 'account/agenda.html', context=context)

@login_required(login_url='/login/')
def wor_calendar_generation(request):
    current_user = UserModel.objects.get(id=request.user.id)
    user_group = current_user.groups.first()
    current_group_user_list = UserModel.objects.filter(groups=user_group)
    print(current_group_user_list)
    ready_selected = current_group_user_list[0].id

    # Collect updates in a list
    updates = []

    for week in WOR_date.objects.all():
        for j in range(current_group_user_list.count()):
            if current_group_user_list[j].id == ready_selected:
                week_id=WOR_date.objects.get(week_number=week.week_number)
                if current_group_user_list[j] == current_group_user_list[current_group_user_list.count() - 1]:
                    print("List breaks on "+ str(current_group_user_list[j]))
                    try:
                        WeekAttendanceRole = WeekAttendanceRoleManager.objects.get(
                            week_id=week_id,
                            users_group=user_group
                        )
                        WeekAttendanceRole.wor_leader = current_group_user_list[j]
                        WeekAttendanceRole.wor_engager = current_group_user_list[0]
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[0].id
                        break
                    except WeekAttendanceRoleManager.DoesNotExist:
                        WeekAttendanceRole = WeekAttendanceRoleManager(
                            week_id=week_id,
                            users_group=user_group,
                            wor_leader=current_group_user_list[j],
                            wor_engager=current_group_user_list[0],
                        )
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[0].id
                        break
                else:
                    print("List continue with user "+ str(current_group_user_list[j]))
                    try:
                        WeekAttendanceRole = WeekAttendanceRoleManager.objects.get(
                            week_id=week_id,
                            users_group=user_group
                        )
                        WeekAttendanceRole.wor_leader = current_group_user_list[j]
                        WeekAttendanceRole.wor_engager = current_group_user_list[j + 1]
                        print("WeekAttendanceRole.wor_engager"+ str(ready_selected))
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[j + 1].id

                        break
                    except WeekAttendanceRoleManager.DoesNotExist:
                        WeekAttendanceRole = WeekAttendanceRoleManager(
                            week_id=week_id,
                            users_group=user_group,
                            wor_leader=current_group_user_list[j],
                            wor_engager=current_group_user_list[j + 1],
                        )
                        updates.append(WeekAttendanceRole)
                        ready_selected = current_group_user_list[j + 1].id
                        break

    # Bulk update the changes
    for update in updates:
        update.save()

    return redirect('/accounts/settings/')

@login_required(login_url='/login/')
def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST, request.FILES)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            time.sleep(1)

            new_user.groups.add(UserModel.objects.get(id = request.user.id).groups.first())
            new_user.last_login = datetime.datetime.now() - timedelta(hours = 8)
            new_user.save()

            RecognitionManagerModel.objects.get_or_create(
                user_profile = UserModel.objects.get(id = new_user.id)

authapp/templates/base.html
{% load static %}
{{ redirect_to_login_immediately }}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="{% static '/img/favicon.png' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <script src="{% static '/js/jquery-3.6.1.js' %}"></script>
    <!-- FoNTs-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    {% block styles %}

    {% endblock styles %}
    <title>WOR {% block page-title %}{% endblock page-title %}</title>
    {% block meta-data %}
    
    {% endblock meta-data %}
  </head>
  <body>

    <header id="header"><!-- class="toggeled" Will be added once click at toggle button -->
      <nav class=".navbar-expand-xl|lg|md|sm menu">
      <div class="logo-block">
          <a class="navbar-brand" href="#">
              <img src="{% static '/img/logo-nestle.png' %}" class="logo-img" alt="Nestle logo">
          
              <span class="logo-text">NBS Lviv Web Content</br> Management Team</span>
          </a>
      </div>
      <div class="accordion" id="accordionPanelsStayOpenExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                <span>Team meeting</span>
              </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
              <div class="accordion-body">
                  <ul class="navbar-nav">
                      {% if request.path == "/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" class="agenda_link" href="{% url 'authapp:agenda' %}"><span class="agenda_image"></span><span class="agenda">Agenda</span></a>
                      </li>
                      {% if request.path == "/attendance/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'attendance:attendance_page' %}"><span class="attendance_image"></span><span class="attendance">Attendance</span></a>
                      </li>
                      {% if request.path == "/she/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'she:she_main' %}"><span class="she_image"></span><span class="she">SHE</span></a>
                      </li>
                      {% if request.path == "/actions/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'actions:action_main' %}"><span class="actions_image"></span><span class="actions">Actions</span></a>
                      </li>
                      {% if request.path == "/improvements/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'improvements:improvements_main' %}"><span class="improvments_image"></span><span class="improvments">Improvments</span></a>
                      </li>
                      {% if request.path == "/recognitions/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'recognitions:recognition_page' %}"><span class="recognition_image"></span><span class="recognition">Recognition</span></a>
                      </li>
                      {% if request.path == "/notice-board/" %}
                      <li class="nav-item active" >
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'notice_board:notice_board' %}"><span class="notice_board_image"></span><span class="notice_board">Measures</span></a>
                      </li>
                    </ul>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                <span>Optional</span>
              </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
              <div class="accordion-body">
                  <ul class="navbar-nav">
                      {% if request.path == "/dashboard/" %}
                      <li class="nav-item active">
                      {% else %}
                      <li class="nav-item ">
                      {% endif %}
                        <a class="nav-link" href="{% url 'authapp:dashboard' %}"><span class="settings_image"></span><span class="settings">Settings</span></a>
                      </li>
                  </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="toggle-wrap"   onclick="addClass()">
          <a href="#">
              <span class="toggle-image"></span>
              <span class="toggle-sb">Toggle sidebar</span>
          </a>
        </div>     
        </nav>
    </header>
    <container id="body">
        <div id="menu"> </div>
        <div class="container-fluid">
            <div class="row">             
                <div id="header-space" class="col-sm-3 col-md-2 col-lg-2"> <!-- class="header_space" Will be added once click at toggle button -->
                    <div class="menu-space"></div>
                </div>
                <div id="content" class="col-sm-9 col-md-10 col-lg-10 red"><!-- class="toggeled_content" Will be added once click at toggle button -->
                    <div class="content-block" >
                        {% block content  %}
                        {% endblock content  %}
                    </div>
                </div>
            </div>
        </div>
    </container>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script>
        function addClass() { 
            const header = document.getElementById("header");
            const content = document.getElementById("content");
            const header_space = document.getElementById("header-space");
            
            header.classList.toggle("toggeled");
            content.classList.toggle("toggeled_content");
            header_space.classList.toggle("header_space");
            // new part
            $(".checkbox-dropdown-list").toggleClass("move")
        }
    </script>
</body>
</html>

authapp/templates/button-loader.html
<style>
    /* .button-loader{
    height: 20px;
    width: 50%;
    text-align: center;
    margin: auto;
    margin-top: -4px;
    display: inline-block;
    vertical-align: top;
    display: block;
    } */
    button{
    display: inline-block;
    border: 1px solid #F5F6F8;
    border-radius: 4px;
    box-shadow: none;
    margin: 8px auto;
    background: #63513D;
    width: 200px;
    height: 40px;
    /* text css */
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 500;
    font-size: 15px;
    line-height: 22px;
    text-align: center;
    letter-spacing: 0.01em;
    color: #FFFFFF;
    }

    /*
    Set the color of the icon
    */
    .button-loader svg path,
    .button-loader svg rect{
    fill: #fff;
    }
</style>
<!-- 8 -->
<div class="button-loader loader--style8" title="7">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        width="20px" height="20px" viewBox="0 0 24 30" style="enable-background:new 0 0 50 50;" xml:space="preserve">
        <rect x="0" y="10" width="4" height="10" fill="#333" opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0s" dur="0.6s" repeatCount="indefinite" />
        </rect>
        <rect x="8" y="10" width="4" height="10" fill="#333"  opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
        </rect>
        <rect x="16" y="10" width="4" height="10" fill="#333"  opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
        </rect>
    </svg>
</div>

authapp/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

{% endblock content %}

authapp/templates/loader.html
<style>
    .loader{
    height: 120px;
    width: 20%;
    text-align: center;
    padding: 1em;
    margin: auto;
    display: inline-block;
    /* vertical-align: top; */
    display: none;
    }

    /*
    Set the color of the icon
    */
    svg path,
    svg rect{
    fill: #63513D;
    }
</style>
<!-- 8 -->
<div class="loader loader--style8" title="7">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        width="50px" height="80px" viewBox="0 0 24 30" style="enable-background:new 0 0 50 50;" xml:space="preserve">
        <rect x="0" y="10" width="4" height="10" fill="#333" opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0s" dur="0.6s" repeatCount="indefinite" />
        </rect>
        <rect x="8" y="10" width="4" height="10" fill="#333"  opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0.15s" dur="0.6s" repeatCount="indefinite" />
        </rect>
        <rect x="16" y="10" width="4" height="10" fill="#333"  opacity="0.2">
            <animate attributeName="opacity" attributeType="XML" values="0.2; 1; .2" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="height" attributeType="XML" values="10; 20; 10" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
            <animate attributeName="y" attributeType="XML" values="10; 5; 10" begin="0.3s" dur="0.6s" repeatCount="indefinite" />
        </rect>
    </svg>
</div>