attendance/urls.py
from django.urls import path
from attendance.views import attendance, attendance_history


urlpatterns = [
    path('', attendance, name='attendance_page'),
    path('history/', attendance_history, name='attendance_history'),
]

she/urls.py
from django.urls import path
from she.views import she_main


urlpatterns = [
    path('', she_main, name='she_main'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new



from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
    path('actions/', include(('actions.urls', 'actions'), namespace='actions')),
    path('attendance/', include(('attendance.urls', 'recognition_page'), namespace='attendance')),
    path('improvements/', include(('improvements.urls', 'improvements'), namespace='improvements')),
    path('notice-board/', include(('notice_board.urls', 'notice_board'), namespace='notice-board')),
    path('recognitions/', include(('recognitions.urls', 'recognition_page'), namespace='recognitions')),
    path('she/', include(('she.urls', 'she_page'), namespace='she')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from datetime import datetime
import calendar
from django.db import models

# Create your models here.
from authapp.models import UserModel
from django.contrib.auth.models import Group

# Create your models here.
class WOR_date (models.Model):
    start_date  =models.DateField(default=datetime.now,blank=True, verbose_name="week start date")
    end_date = models.DateField(default=datetime.now,blank=True, verbose_name="week end date")
    week_number = models.IntegerField(default="0", verbose_name="Week")
    
    def __str__(self):
        return "Week#"+str(self.week_number);
    class Meta:
        ordering = ['week_number']

class WeekAttendanceRoleManager(models.Model):
    week_id =  models.ForeignKey(WOR_date, on_delete=models.CASCADE)
    users_group = models.ForeignKey(Group, blank=False, default="1", on_delete=models.CASCADE, verbose_name="Role`s group")
    wor_leader = models.ForeignKey(UserModel, related_name='wor_leader', on_delete=models.CASCADE, verbose_name="WOR Learder")
    wor_engager = models.ForeignKey(UserModel, related_name='wor_engager', on_delete=models.CASCADE, verbose_name="WOR Engager")

    def __str__(self):
        return "Group#"+ str(self.users_group) +"; Week#"+str(self.week_id.week_number)

    class Meta:
        ordering = ['week_id']

class AttendanceManagerModel(models.Model):
    USER_STATUS = (
        ('present', 'PRESENT'),
        ('absent', 'ABSENT'),
        ('excused', 'EXCUSED'),
        ('on_vacation', 'ON_VACATION'),
        ('comes_later', 'COMES_LATER')
    )
    date = models.ForeignKey(WOR_date, on_delete=models.CASCADE)
    person = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    user_status = models.CharField(max_length=11, choices=USER_STATUS, default='present')

    def __str__(self):
        return "Week#"+str(self.date.week_number) +' / ' +  self.person.username

    class Meta:
        ordering = ['date']

attendance/views.py
from django.shortcuts import render, redirect
from authapp.models import UserModel
from .models import AttendanceManagerModel, WOR_date, WeekAttendanceRoleManager
import datetime
import time
import json
from django.contrib.auth.decorators import login_required
@login_required(login_url='/login/')
# Create your views here.
def attendance(request):
    current_user_group = UserModel.objects.get(id=request.user.id).groups.first()
    current_week = datetime.datetime.now().isocalendar()[1]
    user_list = UserModel.objects.filter(groups=current_user_group)  

    # Filter the week_list queryset based on the current week and the next 11 weeks
    week_list = WOR_date.objects.filter(
        week_number__gt=current_week - 1,
        week_number__lt=current_week + 12
    )
    # Filter week roles by the current user's group and relevant weeks
    week_roles = WeekAttendanceRoleManager.objects.filter(
        users_group=current_user_group,
        week_id__week_number__gt=current_week - 1,
        week_id__week_number__lt=current_week + 12
    )
    # Filter AttendanceManagerModel queryset by users from the same group as the current user
    attendance_list = AttendanceManagerModel.objects.filter(
        person__groups=current_user_group,
        date__week_number__gt=current_week - 1,
        date__week_number__lt=current_week + 12
    ).select_related('person', 'date')    
    if request.POST.get('action') == 'update':
        week_no= int(request.POST.get('current_week'))
        user_status_dictionary = json.loads(request.POST.get('user_status_dictionary'))
        week_to_update = WOR_date.objects.get(week_number = week_no)
        for id in user_status_dictionary:
            try:
                person = UserModel.objects.get(id = id)
                new_attendance = AttendanceManagerModel.objects.get(date = week_to_update, person = person)
                if new_attendance.user_status == user_status_dictionary[id]:
                    continue
                else:     
                    new_attendance.user_status = user_status_dictionary[id]
                    new_attendance.save()
            except AttendanceManagerModel.DoesNotExist:
                new_attendance = AttendanceManagerModel.objects.create(
                    date = WOR_date.objects.get(week_number = week_no),
                    person = UserModel.objects.get(id = id),
                    user_status = user_status_dictionary[id],
                )
                new_attendance.save()
        return render(request, 'attendance-list.html', {
        'attendances': attendance_list, 
        'users': user_list, 
        'current_week': current_week, 
        'week_list' :  week_list,
        'week_roles' : week_roles
        })
    return render(request, 'attendance.html', {
        'attendances': attendance_list, 
        'users': user_list, 
        'current_week': current_week, 
        'week_list' :  week_list,
        'week_roles' : week_roles
        })

def attendance_history(request):
    current_user = UserModel.objects.get(id=request.user.id)
    user_list = UserModel.objects.filter(groups=current_user.groups.first())
    week_roles = WeekAttendanceRoleManager.objects.filter(users_group=current_user.groups.first()) 
    current_week = datetime.datetime.now().isocalendar()[1]

    attendance_list = AttendanceManagerModel.objects.all().select_related('person', 'date')

    week_list = WOR_date.objects.all()

    return render(request, 'attendance-history.html', {
        'attendances': attendance_list,
        'users': user_list,
        'current_week': current_week,
        'week_list': week_list,
        'week_roles': week_roles
    })

attendance/templates/attendance-history.html
{% extends "base.html" %}
{% load static %}
{% block page-title %} | Attendance{% endblock page-title %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/attendance.css' %}">
{% endblock styles %}
{% block content %}
<div>  
    <div class="btns">
        <a href="{% url 'attendance:attendance_page' %}" onclick="openForm()">
            <img src="{% static '/img/back.png' %}" alt="update page"> 
            <span class="add">Back to Attendance</span>
        </a>
        <div class="weeks_btns">
            <button class="button" id="prev"> Back</button>
            <button class="button" id="next">Next</button>
        </div>
    </div>
    <h2 class="page-title">Attendance history</h2>
    <div class="icons_info">
        <ul class="leader_engager_icons">
            <li class="leader_info"><img src="{% static '/img/leader_icon_drk.svg' %}" alt="leader"><span>WOR LEADER</span></li>
            <li class="leader_info"><img class="padding_info" src="{% static '/img/engager_icon_drk.svg ' %}" alt="engager"><span>COMUNICATION ENGAGER</span></li>
        </ul>
        <ul class="leader_engager_status">
            <li class="leader_info"><span class="circle_present"></span><span>Yes, present</span></li>
            <li class="leader_info"><span class="circle_absent"></span><span>No, not present</span></li>
            <li class="leader_info"><span class="circle_excused "></span><span>Excused (back-up in place)</span></li>
            <li class="leader_info"><span class="circle_vacation "></span><span>On Vacation</span></li>
        </ul>
    </div>
</div>
<div class="attendance_content">
    <div class="names">
        <table>
            <tr>
                    <td ><span>Names</span><span><br>IMS Team</br></span></td>
            </tr>
            {% for user in users%} 
                <tr>
                    <td>{{user.first_name}} {{user.last_name}}</td>
                </tr>
            {% endfor%}
        </table>
    </div>
    <div class="weeks">
        <table class="carousel">
            <tbody class="carouselContainer">
                <tr >
                    {% for week in week_list%}
                        <td class="slides"><span>Week {{week.week_number}}</span><span><br>{{week.start_date|date:"m.d"}} - {{week.end_date|date:"m.d"}}</br></span></td>   
                    {% endfor%} 
                </tr>
                {% for user in users%}     
                    <tr id="{{user.id}}">
                        {% for week in week_list%}
                            <td class="slides" id="week.week_number">
                                {% for week_role in week_roles%}
                                    {% if week_role.wor_leader.pk == user.pk and week_role.week_id.week_number == week.week_number  %}
                                        <div class="
                                        {% for attendance in attendances%}
                                            {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                                {{attendance.user_status}}
                                            {% endif %}
                                        {% endfor%}   
                                        leader"><span></span></div>
                                    {% elif week_role.wor_engager.pk == user.pk and week_role.week_id.week_number == week.week_number  %}
                                        <div class="
                                        {% for attendance in attendances%}
                                            {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                                {{attendance.user_status}}
                                            {% endif %}
                                        {% endfor%} 
                                        engager"><span></span></div>
                                    {% elif week_role.week_id.week_number == week.week_number%}
                                        <div class="
                                        {% for attendance in attendances%}
                                            {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                                {{attendance.user_status}}
                                            {% endif %}
                                        {% endfor%}             
                                        "><span></span></div>
                                    {% endif %}
                                {% endfor%} 
                            </td>
                        {% endfor%}
                    </tr>        
                {% endfor%}                   
            </tbody>
        </table>
    </div>
</div>
<script src="{% static '/js/attendance.js' %}"></script>

<script>
    // $(document).ready(function () {
    //     $('div.attendance_content').css('display', 'block');
    // });
    ////////////////// Carousel /////////////////
    var carouselContainer = document.querySelector(".carouselContainer");  
    var slides = document.querySelectorAll('.slides');  
    var next = document.querySelector('#next');  
    var prev = document.querySelector('#prev');  
    var counter = 0;  
    if ( (parseInt("{{current_week}}") -1) > 47){
        counter = 47
    } else {
        counter = parseInt('{{current_week}}') -1
    }
    var size = slides[0].clientWidth +1;  
    console.log(size);
    carouselContainer.style.transform = 'translateX(' + (-size * counter)   + 'px';  
    console.log(carouselContainer.style.transform);
    next.addEventListener('click',()=>{  
    if (counter>=47)return;  
        carouselContainer.style.transition = 'transform 0.4s ease-in-out'; 
        counter++;
        carouselContainer.style.transform = 'translateX(' + (-size * counter )  + 'px';  
    });  
    prev.addEventListener('click',()=>{  
    if (counter<=0)return;  
        carouselContainer.style.transition = 'transform 0.4s ease-in-out';  
        counter--;  
        carouselContainer.style.transform = 'translateX(' + (-size * counter ) + 'px';  
    });  
    carouselContainer.addEventListener('transitionend',()=>{  
    console.log(slides[counter]);  
    if(slides[counter].id ==='lastslide'){  
        carouselContainer.style.transition = 'none';  
        counter = slides.length - 2;      
        carouselContainer.style.transform = 'translateX(' + (-size * counter ) + 'px';  
    }  
    });  
    carouselContainer.addEventListener('transitionend',()=>{  
    console.log(slides[counter]);  
    if(slides[counter].id ==='firstslide'){  
        carouselContainer.style.transition = 'none';  
        counter = slides.length - counter;      
        carouselContainer.style.transform = 'translateX(' + (-size * counter ) + 'px';  
    }  
    });
</script>

{% endblock content %}

attendance/templates/attendance-list.html
<table class="carousel">
    <tbody class="carouselContainer">
        <tr >
            {% for week in week_list%}
                <td class="slides"><span>Week {{week.week_number}}</span><span><br>{{week.start_date|date:"m.d"}} - {{week.end_date|date:"m.d"}}</br></span></td>   
            {% endfor%} 
        </tr>
        {% for user in users%}     
            <tr id="{{user.id}}">
                {% for week in week_list%}
                    <td class="slides" id="week.week_number">
                        {% for week_role in week_roles%}
                            {% if week_role.wor_leader.pk == user.pk and week_role.week_id.week_number == week.week_number  %}
                                <div class="
                                {% for attendance in attendances%}
                                    {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                        {{attendance.user_status}}
                                    {% endif %}
                                {% endfor%}   
                                leader"><span></span></div>
                            {% elif week_role.wor_engager.pk == user.pk and week_role.week_id.week_number == week.week_number  %}
                                <div class="
                                {% for attendance in attendances%}
                                    {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                        {{attendance.user_status}}
                                    {% endif %}
                                {% endfor%} 
                                engager"><span></span></div>
                            {% elif week_role.week_id.week_number == week.week_number%}
                                <div class="
                                {% for attendance in attendances%}
                                    {% if user.pk == attendance.person.pk and week.week_number == attendance.date.week_number %}
                                        {{attendance.user_status}}
                                    {% endif %}
                                {% endfor%}             
                                "><span></span></div>
                            {% endif %}
                        {% endfor%} 
                    </td>
                {% endfor%}
            </tr>        
        {% endfor%}                   
    </tbody>
</table>

attendance/templates/attendance.html
{% extends "base.html" %}
{% load static %}
{% block page-title %} | Attendance{% endblock page-title %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/attendance.css' %}">
{% endblock styles %}
{% block content %}
<div>  
    <div class="btns">
        <a href="#" onclick="openForm()"><img src="{% static '/img/update.png' %}" alt="update page"> <span class="update">Update</span></a>
        <a href="{% url 'attendance:attendance_history' %}">
            <img src="{% static '/img/view.png' %}" alt="View history">
            <span class="add-task">View history</span>
        </a>
    </div>
    <h2 class="page-title">Attendance</h2>
    <div class="icons_info">
        <ul class="leader_engager_icons">
            <li class="leader_info"><img src="{% static '/img/leader_icon_drk.svg' %}" alt="leader"><span>WOR LEADER</span></li>
            <li class="leader_info"><img class="padding_info" src="{% static '/img/engager_icon_drk.svg ' %}" alt="engager"><span>COMUNICATION ENGAGER</span></li>
        </ul>
        <ul class="leader_engager_status">
            <li class="leader_info"><span class="circle_present"></span><span>Yes, present</span></li>
            <li class="leader_info"><span class="circle_absent"></span><span>No, not present</span></li>
            <li class="leader_info"><span class="circle_excused "></span><span>Excused (back-up in place)</span></li>
            <li class="leader_info"><span class="circle_vacation "></span><span>On Vacation</span></li>
        </ul>
    </div>
</div>
<div class="attendance_content">
    <div class="names">
        <table>
            <tr>
                    <td ><span>Names</span><span><br>IMS Team</br></span></td>
            </tr>
            {% for user in users%} 
                <tr>
                    <td>{{user.first_name}} {{user.last_name}}</td>
                </tr>
            {% endfor%}
        </table>
    </div>
    <div class="weeks">
        {% include 'attendance-list.html' %}
    </div>
</div>
<!------------ Form POP-UP ------------->
<div class="form_container" id="popup">
    <div class="attendance_form">
        <h3 class="form-title">Week #<span id="current_week_id">{{current_week}}</span> Attendance: Provide an action</h3>
        <form method="post" id="attendance_update_form">
            {% csrf_token %}
            <div class="users_container">
                {% for user in users%}
                    <div class="user_to_action">
                        <div class="user_information">
                            <div class="user_image"> <img alt="{{user.first_name}} {{user.last_name}}" src="{{user.user_image.url}}"> </div>
                            <div class="user_name_block">
                                <span class="user_name">{{user.first_name}} {{user.last_name}}</span>
                            </div>
                        </div>
                        <fieldset class="action_buttons">
                            <div class="button_item present">
                                <input type="radio" id="present_{{user.id}}" name="status_user_{{user.id}}" value="present" checked>
                                <label for="present_{{user.id}}">Present</label>
                            </div>                   
                            <div class="button_item absent">
                                <input type="radio" id="absent_{{user.id}}" name="status_user_{{user.id}}" value="absent"
                                {% for attendance in attendances%}
                                {{% if user.pk == attendance.person.pk and attendance.date.week_number == current_week %}                                        
                                        {% if attendance.user_status == 'absent' %}   
                                            checked
                                        {% endif %}
                                    {% endif %}
                                {% endfor%}
                                >
                                <label for="absent_{{user.id}}">Not present </label>
                            </div>                                        
                            <div class="button_item excused">
                                <input type="radio" id="excused_{{user.id}}" name="status_user_{{user.id}}" value="excused"
                                {% for attendance in attendances%}
                                    {% if user.pk == attendance.person.pk and attendance.date.week_number == current_week %}
                                        {% if attendance.user_status == 'excused' %}   
                                            checked 
                                        {% endif %}
                                    {% endif %}
                                {% endfor%}
                                >
                                <label for="excused_{{user.id}}">Excused</label>
                            </div>                                            
                            <div class="button_item on_vacation">
                                <input type="radio" id="on_vacation_{{user.id}}" name="status_user_{{user.id}}" value="on_vacation"
                                {% for attendance in attendances%}
                                    {% if user.pk == attendance.person.pk and attendance.date.week_number == current_week %}
                                        {% if attendance.user_status == 'on_vacation' %}   
                                            checked 
                                        {% endif %}
                                    {% endif %}
                                {% endfor%}
                                >
                                <label for="on_vacation_{{user.id}}">On Vacation</label>
                            </div>
                        </fieldset>
                    </div>
                {% endfor %}
            </div>
            <div class="button_form_field">
                <button class="button submit" type="submit">Confirm</button>
                <button style="display: none;" class="button button-loader">{% include 'button-loader.html' %}</button>
                <button type="button" onclick="closeForm()" class="button cancel">Cancel</button>  
            </div> 
        </form>        
    </div>
</div>
<script src="{% static '/js/attendance.js' %}"></script>
<script>
    $(document).on('submit', '#attendance_update_form',function(e){
        e.preventDefault();
        $('.submit').hide();
        $('.button-loader').show();
        
        var user_selected_statuses_list = $(this).find("input[type='radio']:checked");
        var user_status_dictionary = {};

        for (let i=0; i<user_selected_statuses_list.length;i++){
            user_status_dictionary[(user_selected_statuses_list[i].name).replace('status_user_', '')] = user_selected_statuses_list[i].value;
        }

        $.ajax({
            type:'POST',
            url:"{% url 'attendance:attendance_page' %}",
            data:{
                current_week: $('#current_week_id').html(),
                user_status_dictionary: JSON.stringify(user_status_dictionary),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'update'
            },
            success:function(response){
                $('.confirm').show();
                $('.button-loader').hide();
                var element = document.getElementById("popup");
                element.classList.remove("show");
                document.body.style.overflowY = "scroll";
                $(".weeks").html(response);
            },
            error : function(xhr,errmsg,err) {
                $('.confirm').show();
                $('.button-loader').hide();
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        });
    });  
    
</script>
{% endblock content %}